name: analytics_integration
description: An example of Analytics integration in  Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.9
  firebase_analytics: ^12.4.6
  firebase_core: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - asset/