// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnRhs8FEly8Ro_8vZpyxNcDWeQC33EuIc',
    appId: '1:651435915042:web:33ad8a8f66452e0fb1577b',
    messagingSenderId: '651435915042',
    projectId: 'firebase-twitter-login-upahar',
    authDomain: 'fir-twitter-login-upahar.firebaseapp.com',
    storageBucket: 'firebase-twitter-login-upahar.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ9K_Tj_gdGc_WgsJ-MQPYF1YRIm4EHNs',
    appId: '1:651435915042:ios:bd5b9865f9a5bbb6b1577b',
    messagingSenderId: '651435915042',
    projectId: 'firebase-twitter-login-upahar',
    storageBucket: 'firebase-twitter-login-upahar.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTwitterSignIn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnRhs8FEly8Ro_8vZpyxNcDWeQC33EuIc',
    appId: '1:651435915042:web:5e426e685fcc0d9cb1577b',
    messagingSenderId: '651435915042',
    projectId: 'firebase-twitter-login-upahar',
    authDomain: 'fir-twitter-login-upahar.firebaseapp.com',
    storageBucket: 'firebase-twitter-login-upahar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ9K_Tj_gdGc_WgsJ-MQPYF1YRIm4EHNs',
    appId: '1:651435915042:ios:bd5b9865f9a5bbb6b1577b',
    messagingSenderId: '651435915042',
    projectId: 'firebase-twitter-login-upahar',
    storageBucket: 'firebase-twitter-login-upahar.firebasestorage.app',
    iosBundleId: 'com.example.firebaseTwitterSignIn',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_XhLYl_TjNND4wZOYGCVyAJEoJPPNd6k',
    appId: '1:651435915042:android:2936ed840e5c74cbb1577b',
    messagingSenderId: '651435915042',
    projectId: 'firebase-twitter-login-upahar',
    storageBucket: 'firebase-twitter-login-upahar.firebasestorage.app',
  );

}