// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZcBxEiSUSbrJdh2TqJfO4ySu_RRydpmk',
    appId: '1:845969639687:web:5e46819431e9bc03ba9da2',
    messagingSenderId: '845969639687',
    projectId: 'todoapp-cbd21',
    authDomain: 'todoapp-cbd21.firebaseapp.com',
    storageBucket: 'todoapp-cbd21.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJUJmEdax-zup4YIu4-Jc_E8VUaga-QC4',
    appId: '1:845969639687:android:fa41ba9dffeec1edba9da2',
    messagingSenderId: '845969639687',
    projectId: 'todoapp-cbd21',
    storageBucket: 'todoapp-cbd21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeRsZEhruSSbrrn-ayR5Nh5uuv-nTXeVs',
    appId: '1:845969639687:ios:3416ba56912c41d1ba9da2',
    messagingSenderId: '845969639687',
    projectId: 'todoapp-cbd21',
    storageBucket: 'todoapp-cbd21.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeRsZEhruSSbrrn-ayR5Nh5uuv-nTXeVs',
    appId: '1:845969639687:ios:e5ec4ea82076de1cba9da2',
    messagingSenderId: '845969639687',
    projectId: 'todoapp-cbd21',
    storageBucket: 'todoapp-cbd21.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
